$(function(){
	$('#fullpage').fullpage({
		navigation:true,
		navigationPosition:'left',
		anchors:['s1','s2','s3','s4','s5'],
		afterLoad:function(link,index){
        	switch(link){
        		case 's2':fn2();
        		break;
        		case 's3':fn3();
        		break;
        		case 's4':fn4();
        		break;
        		case 's5':fn5();
        		break;
        	}
		},
		//index,nextIndex,direction
		//离开的序号 到达的序号 滚动的方向
		onLeave:function(index,nextIndex,direction){
            switch(index){
            	case 2:back2(); break;
            	case 3:back3(); break;
            	case 4:back4(); break;
            	case 5:back5(); break;
            }
		}
	})
	var fn2=function(){
		move('.logo')
	    .set('transform', 'translate3d(0,0,0)')
	    .set('opacity', '1')
	    .end();
        move('.text')
	    .scale(1)
	    .delay('0.5s')
	    .end();
	    move('.lists ul li:nth-child(1)')
	    .set('opacity', '1')
	    .set('transform', 'translate3d(0,0,0)')
	    .duration('0.4s')
	    .delay('0.5s')
	    .end();
	    move('.lists ul li:nth-child(2)')
	    .set('opacity', '1')
	    .set('transform', 'translate3d(0,0,0)')
	    .duration('0.4s')
	    .delay('1s')
	    .end();
	    move('.lists ul li:nth-child(3)')
	    .set('opacity', '1')
	    .set('transform', 'translate3d(0,0,0)')
	    .duration('0.4s')
	    .delay('1.5s')
	    .end();
	    move('.lists ul li:nth-child(4)')
	    .set('opacity', '1')
	    .set('transform', 'translate3d(0,0,0)')
	    .duration('0.4s')
	    .delay('2s')
	    .end();
	    move('.lists ul li:nth-child(5)')
	    .set('opacity', '1')
	    .set('transform', 'translate3d(0,0,0)')
	    .duration('0.4s')
	    .delay('2.5s')
	    .end();
	}
	var back2=function(){
		move('.logo')
	    .set('opacity', 0)
	    .set('transform','translate3d(0,-40px,0)')
	    .delay('0.5s')
	    .end();
	    move('.text')
	    .set('transform', 'scale(0)')
	    .delay('0.5s')
	    .end();
		move('.lists ul li:nth-child(1)')
	    .set('opacity', '0')
	    .set('transform', 'translate3d(0,100px,0)')
	    .delay('0.5s')
	    .end();
	    move('.lists ul li:nth-child(2)')
	    .set('opacity', '0')
	    .set('transform', 'translate3d(0,100px,0)')
	    .delay('0.5s')
	    .end();
	    move('.lists ul li:nth-child(3)')
	    .set('opacity', '0')
	    .set('transform', 'translate3d(0,100px,0)')
	    .delay('0.5s')
	    .end();
	    move('.lists ul li:nth-child(4)')
	    .set('opacity', '0')
	    .set('transform', 'translate3d(0,100px,0)')
	    .delay('0.5s')
	    .end();
	    move('.lists ul li:nth-child(5)')
	    .set('opacity', '0')
	    .set('transform', 'translate3d(0,100px,0)')
	    .delay('0.5s')
	    .end();
	} 
	var fn3=function(){
		move('.container .col-one h3')
		.set('transform','translate3d(0,0,0)')
		.set('opacity',1)
		.duration('0.5')
		.delay('0.5s')
		.end()
		move('.container .col-one .text_s3')
		.set('transform','translate3d(0,0,0)')
		.set('transform','scale(1)')
		.set('opacity',1)
		.duration('1')
		.end()
		move('.list_s3 .groupone li:nth-child(1)')
	    .set('transform', 'translate3d(0,0,0)')
	    .set('opacity', 1)
	    .duration('0.4s')
		.end()
		move('.list_s3 .groupone li:nth-child(2)')
	    .set('transform','translate3d(0,0,0)')
	    .set('opacity', 1)
	    .duration('0.4s')	
	    .delay('0.4s')
		.end()
		move('.list_s3 .groupone li:nth-child(3)')
	    .set('transform', 'translate3d(0,0,0)')
	    .set('opacity', 1)
	    .duration('0.4s')
	    .delay('0.8s')	
		.end()
		move('.list_s3 .groupone li:nth-child(4)')
	    .set('transform', 'translate3d(0,0,0)')
	    .set('opacity', 1)
	    .duration('0.4s')
	    .delay('1.2s')		
		.end()
		move('.list_s3 .groupone li:nth-child(5)')
	    .set('transform', 'translate3d(0,0,0)')
	    .set('opacity', 1)
	    .duration('0.4s')
	    .delay('1.6s')			
		.end(function(){
			move('.list_s3 .grouptwo li:nth-child(1)')
			.set('transform', 'translate3d(-23px,-120px,0)')
			.set('opacity',1)
			.duration('0.8s')
			.delay('0.5s')
		    .end()				
		    move('.list_s3 .grouptwo li:nth-child(2)')
			.set('transform', 'translate3d(-20px,-100px,0)')
			.set('opacity',1)
			.duration('0.8s')
			.delay('0.9s')
		    .end()
		    move('.list_s3 .grouptwo li:nth-child(3)')
			.set('transform', 'translate3d(20px,-100px,0)')
			.set('opacity',1)
			.duration('0.8s')
			.delay('1s')
		    .end()
		    move('.list_s3 .grouptwo li:nth-child(4)')
			.set('transform', 'translate3d(30px,-80px,0)')
			.set('opacity',1)
			.duration('0.8s')
			.delay('0.8s')
		    .end()
		    move('.list_s3 .grouptwo li:nth-child(5)')
			.set('transform', 'translate3d(-30px,-70px,0)')
			.set('opacity',1)
			.duration('0.8s')
			.delay('0.6s')
		    .end()
		})
		
	}
	var back3=function(){
		move('.list_s3 .groupone li:nth-child(1)')
	    .set('transform', 'translate3d(-200px,-330px,0)')
	    .set('opacity', 0)
	    .delay('1s')
	    .duration('0.1s')
	    .end();
	    move('.list_s3 .groupone li:nth-child(2)')
	    .set('transform', 'translate3d(-100px,-330px,0)')
	    .set('opacity', 0)
	    .delay('1s')
	    .duration('0.1s')
	    .end();
	    move('.list_s3 .groupone li:nth-child(3)')
	    .set('transform', 'translate3d(0,-330px,0)')
	    .set('opacity', 0)
	    .delay('1s')
	    .duration('0.1s')
	    .end();
	    move('.list_s3 .groupone li:nth-child(4)')
	    .set('transform', 'translate3d(100px,-330px,0)')
	    .set('opacity', 0)
	    .delay('1s')
	    .duration('0.1s')
	    .end();
	    move('.list_s3 .groupone li:nth-child(5)')
	    .set('transform', 'translate3d(200px,-330px,0)')
	    .set('opacity', 0)
	    .delay('1s')
	    .duration('0.1s')
	    .end();
	    move('.list_s3 .grouptwo li:nth-child(1)')
		.set('transform', 'translate3d(0,0,0)')
		.duration('0.1s')
		.set('opacity', 0)
	    .end()
	    move('.list_s3 .grouptwo li:nth-child(2)')
		.set('transform', 'translate3d(0,0,0)')
		.duration('0.1s')
		.set('opacity', 0)
	    .end()
	    move('.list_s3 .grouptwo li:nth-child(3)')
		.set('transform', 'translate3d(0,0,0)')
		.duration('0.1s')
		.set('opacity', 0)
	    .end()
	    move('.list_s3 .grouptwo li:nth-child(4)')
		.set('transform', 'translate3d(0,0,0)')
		.duration('0.1s')
		.set('opacity', 0)
	    .end()
	    move('.list_s3 .grouptwo li:nth-child(5)')
		.set('transform', 'translate3d(0,0,0)')
		.duration('0.1s')
		.set('opacity', 0)
	    .end()
	    move('.container .col-one h3')
		.set('transform','translate3d(0,-50px,0)')
		.set('opacity',0)
		.duration('0.5')
		.end()
		move('.container .col-one .text_s3')
		.set('transform','translate3d(0,-200px,0)')
		.set('opacity',0)
		.duration('1')
		.end()
	}
	var fn4=function(){
		move('.section_s4 h3')
		.set('transform', 'translate3d(0,-80px,0)')
		.set('opacity',1)
		.duration('0.7s')
		.end()
		move('.section_s4 .text_s4')
		.set('transform', 'translate3d(0,-50px,0)')
		.set('opacity', 1)
		.duration('0.7s')
		.delay('0.5s')
		.end()
		move('.imgbox img')
		.set('transform', 'translate3d(0,0,0)')
		.set('opacity',1)
		.duration('0.7s')
	    .end(function(){
	    		 move('.list_s4 li:nth-child(1)')
	    		.set('transform', 'translate3d(-240px,50px,0)')
	    		.set('opacity',1)
	    		.duration('0.4s')
	    	    .end()
	    	     move('.list_s4 li:nth-child(2)')
	    		.set('transform', 'translate3d(-150px,-80px,0)')
	    		.set('opacity',1)
	    		.duration('0.4s')
	    		.delay('0.4s')
	    	    .end()
	    	     move('.list_s4 li:nth-child(3)')
	    		.set('transform', 'translate3d(0,-150px,0)')
	    		.set('opacity',1)
	    		.duration('0.4s')
	    		.delay('0.8s')
	    	    .end()
	    	     move('.list_s4 li:nth-child(4)')
	    		.set('transform', 'translate3d(150px,-80px,0)')
	    		.set('opacity',1)
	    		.duration('0.4s')
	    		.delay('1.2s')
	    	    .end()
	    	     move('.list_s4 li:nth-child(5)')
	    		.set('transform', 'translate3d(240px,50px,0)')
	    		.set('opacity',1)
	    		.duration('0.4s')
	    		.delay('1.6s')
	    	    .end()
	    	})
	}
	var back4=function(){
		move('.section_s4 h3')
		.set('transform', 'translate3d(0,-140px,0)')
		.set('opacity',0)
		.duration('0.1s')
		.delay('1s')
		.end()
		move('.section_s4 .text_s4')
		.set('transform', 'translate3d(0,-150px,0)')
		.set('opacity', 0)
		.duration('0.1s')
		.delay('1s')
		.end()
		move('.imgbox img')
		.set('transform', 'translate3d(0,-130px,0)')
		.set('opacity',0)
		.duration('0.1s')
		.delay('1s')
	    .end()
		move('.list_s4 li:nth-child(1)')
		.set('transform', 'translate3d(0,0,0)')
		.set('opacity',0)
		.duration('0.1s')
		.delay('1s')
	    .end()
	     move('.list_s4 li:nth-child(2)')
		.set('transform', 'translate3d(0,0,0)')
		.set('opacity',0)
		.duration('0.1s')
		.delay('1s')
	    .end()
	     move('.list_s4 li:nth-child(3)')
		.set('transform', 'translate3d(0,0,0)')
		.set('opacity',0)
		.duration('0.1s')
		.delay('1s')
	    .end()
	     move('.list_s4 li:nth-child(4)')
		.set('transform', 'translate3d(0,0,0)')
		.set('opacity',0)
		.duration('0.1s')
		.delay('1s')
	    .end()
	     move('.list_s4 li:nth-child(5)')
		.set('transform', 'translate3d(0,0,0)')
		.set('opacity',0)
		.duration('0.1s')
		.delay('1s')
	    .end()
	}
	var fn5=function(){
		move('.section .section_s5 h3')
		.set('transform', 'translate3d(0,0,0)')
		.set('opacity', 1)
		.duration('0.5s')
		.end()
		move('.section .section_s5 .text_s5')
		.set('transform', 'translate3d(0,0,0)')
		.set('opacity',1)
		.duration('0.6s')
		.end()
		move('.section:nth-child(5) .list_s5 ul li:nth-child(1)')
		.set('transform', 'scale(1)')
		.duration('0.4s')
		.end()
		move('.section:nth-child(5) .list_s5 ul li:nth-child(2)')
		.set('transform', 'scale(1)')
		.duration('0.4s')
		.end()
		move('.section:nth-child(5) .list_s5 ul li:nth-child(3)')
		.set('transform', 'scale(1)')
		.duration('0.4s')
		.end()
		move('.section:nth-child(5) .list_s5 ul li:nth-child(4)')
		.set('transform', 'scale(1)')
		.duration('0.4s')
		.end()
		move('.section:nth-child(5) .list_s5 ul li:nth-child(5)')
		.set('transform', 'scale(1)')
		.duration('0.4s')
		.end()
	}
	var back5=function(){
		move('.section .section_s5 h3')
		.set('transform', 'translate3d(0,-100px,0)')
		.set('opacity', 0)
		.duration('0.1s')
		.delay('1s')
		.end()
		move('.section .section_s5 .text_s5')
		.set('transform', 'translate3d(0,-200px,0)')
		.set('opacity',0)
		.duration('0.1s')
		.delay('1s')
		.end()
		move('.section:nth-child(5) .list_s5 ul li:nth-child(1)')
		.set('transform', 'scale(0)')
		.duration('0.1s')
		.delay('1')
		.end()
		move('.section:nth-child(5) .list_s5 ul li:nth-child(2)')
		.set('transform', 'scale(0)')
		.duration('0.1s')
		.delay('1')
		.end()
		move('.section:nth-child(5) .list_s5 ul li:nth-child(3)')
		.set('transform', 'scale(0)')
		.duration('0.1s')
		.delay('1')
		.end()
		move('.section:nth-child(5) .list_s5 ul li:nth-child(4)')
		.set('transform', 'scale(0)')
		.duration('0.1s')
		.delay('1')
		.end()
		move('.section:nth-child(5) .list_s5 ul li:nth-child(5)')
		.set('transform', 'scale(0)')
		.duration('0.1s')
		.delay('1')
		.end()
	}
})